import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "@/components/providers";
import { ThemeProvider } from "@/components/theme-provider";
import { cookies } from "next/headers";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { DashboardSidebar } from "@/features/dashboard/components/dashboard-sidebar";
import { DashboardHeader } from "@/components/dashboard-header";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const cookieStore = await cookies();
  const sidebarState = cookieStore.get("sidebar_state");
  const defaultOpen = sidebarState ? sidebarState.value === "true" : true;
  const activeOrgId = cookieStore.get("activeOrgId")?.value;

  let currentOrg = null;
  let memberships: any[] = [];

  if (session?.user?.id) {
    memberships = await prisma.membership.findMany({
      where: { userId: session.user.id },
      include: { organization: true },
    });

    if (activeOrgId) {
      currentOrg = memberships.find((m) => m.organizationId === activeOrgId)?.organization;
    }

    if (!currentOrg && memberships.length > 0) {
      currentOrg = memberships[0].organization;
    }
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers session={session}>
            <SidebarProvider defaultOpen={defaultOpen} className="h-svh">
              <DashboardSidebar
                currentOrg={currentOrg}
                memberships={memberships}
              />
              <SidebarInset className="min-h-0 min-w-0">
                <div className="flex flex-col h-full w-full">
                  <DashboardHeader />
                  <main className="flex-1 min-h-0 overflow-auto">
                    {children}
                  </main>
                </div>
              </SidebarInset>
            </SidebarProvider>
          </Providers>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
